import type { Metadata } from "next";

import { getSession } from "./auth"
import Providers from "./providers"

import './globals.css'

import 'cirrus-ui';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession()

  return (
      <html lang="en">
          <body>
          <div className="header unselectable header-animated">
         <div className="header-brand">
            <div className="nav-item no-hover">
               <h6 className="title"><img src="/logo/logo.png" style={{height: "48pt"}} /></h6>
            </div>
         </div>
      </div>
        <section className="section u-text-center">
            <div className="content u-center">
              <Providers session={session}>
                  {children}
              </Providers>
            </div>
        </section>
          </body>
      </html>
  )
}