import type { Metadata } from "next";

import { getSession } from "./auth"
import Providers from "./providers"

import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession()

  return (
      <html lang="en">
          <body>
              <Providers session={session}>
                  {children}
              </Providers>
          </body>
      </html>
  )
}